{% set version = "2.15" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bipartite
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bipartite_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bipartite/bipartite_{{ version }}.tar.gz
  sha256: 86b830010477864e108d4b6e42d433025d3bfd61d1fdffcae63befbd52e5213f

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-fields
    - r-igraph
    - r-permute
    - r-sna
    - r-vegan
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-fields
    - r-igraph
    - r-permute
    - r-sna
    - r-vegan

test:
  commands:
    - $R -e "library('bipartite')"           # [not win]
    - "\"%R%\" -e \"library('bipartite')\""  # [win]

about:
  home: https://github.com/biometry/bipartite
  license: GPL
  summary: "Functions to visualise webs and calculate a series of indices commonly used to describe pattern in (ecological) webs. It focuses on webs consisting of\
    \ only two levels (bipartite), e.g. pollination webs or predator-prey-webs. Visualisation is important to get an idea of what we are actually looking at, while\
    \ the indices summarise different aspects of the web's topology. "
  license_family: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: bipartite
# Type: Package
# Title: Visualising Bipartite Networks and Calculating Some (Ecological) Indices
# Version: 2.13
# Date: 2019-05-21
# Author: Carsten F. Dormann, Jochen Fruend and Bernd Gruber, with additional code from Stephen Beckett, Mariano Devoto, Jose Iriondo, Tove Opsahl, Rouven Strauss and Diego Vazquez, also based on C-code developed by Nils Bluethgen, Aaron Clauset/Rouven Strauss and Miguel Rodriguez-Girones
# Maintainer: Carsten F. Dormann <carsten.dormann@biom.uni-freiburg.de>
# Depends: vegan, sna
# Imports: fields, igraph, MASS, methods, permute
# Suggests: knitr
# LazyData: TRUE
# ByteCompile: TRUE
# NeedsCompilation: yes
# VignetteBuilder: utils
# URL: https://github.com/biometry/bipartite
# Description: Functions to visualise webs and calculate a series of indices commonly used to describe pattern in (ecological) webs. It focuses on webs consisting of only two levels (bipartite), e.g. pollination webs or predator-prey-webs. Visualisation is important to get an idea of what we are actually looking at, while the indices summarise different aspects of the web's topology.
# License: GPL
# Packaged: 2019-05-21 14:50:53 UTC; Carsten
# Repository: CRAN
# Date/Publication: 2019-05-21 17:20:04 UTC
