travis:
  secure:
    BINSTAR_TOKEN: mkhtHvMlg72Agg+bZRdoSWeuNsBGbWJV71JmHiHuF2ml4KzzvG6YwozLzzCETkmch2CNH/nGN6I4+3vkx96R2NhRifoUPRWcaRwzwcVaJoThfGNrJg9NP08Rd/JGfgX+2YxIkTXa6BvlGbz997SgezwDeCJcJ01lx7VSlN9w4YMc1RhF5C48+m8bljWpR40jd2ncD/kw8PQWovmtGT6pLq7PwowxquI0eDqnIq5jQDGQCKP1l6ktWt/jHjsebaJn2KRa+/lW9Ve864M8riiB4YvWHqSBG+vxS02XHq0gbczHRGFuen+ZWEAFv/ZCrXj0EhV0qA7gyexijkJM04ybwh4BCQGx4GdOEaDrcw0REiFmVqUjUq785PQT0dRJPaLF2+VY+AwRo8bkTI+eKmzmQxHaHf9GcAeopI+j/XuwElQxt9CUfKpV/oBk69yG585R/RqVondXsRmYELdDSmuful4XxmcF8UOvJ5SXjePLEgBb5K/f2vJKGXoKxIiMCxCS4QjF+nRtRhwO3xWSK9ReeCo1fNfG16etF+dUTmv1cPwNLtkzSqSCDlji8OHc5P1JB3lEvNdWovh/L6oUydJ1Z4nZHwN15gkb1y4wBXptk4MN3nig2XfExGCqLKLUkBUeGlk6AED2NSJnl7A/WZn4Q6ekVdW9HPx++jPwRIvhXCg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
